sync program :
- tb_m_departement
- tb_m_employee
- tb_m_user
sync MASTER product :
- tb_m_code
- tb_m_code_detail
- tb_m_product
- tb_m_product_code
- tb_template_code
- tb_template_code_det
- tb_m_design
- tb_m_design_code
- tb_m_design_price
- tb_season
- tb_season_delivery
- tb_season_orign
- tb_m_sample
- tb_m_uom
- tb_lookup_status
- tb_lookup_design_price_type
